##R code for plot3
setwd("E:/statistics/coursera/repository/exploratorydataanalysis")
alldata<-read.csv2("household_power_consumption.txt")
alldata$Date<-as.Date(as.character(alldata$Date),format="%d/%m/%Y")
subsetdata<-alldata[alldata$Date=="2007-2-1"|alldata$Date=="2007-2-2",]
y<-character()
y<-paste(as.character(subsetdata$Date),as.character(subsetdata$Time),sep=",")
subsetdata$Time<-strptime(y,"%Y-%m-%d,%H:%M:%S")
subsetdata$Time<-as.POSIXct(subsetdata$Time)
subsetdata$Sub_metering_1<-as.numeric(levels(subsetdata$Sub_metering_1)[subsetdata$Sub_metering_1])
subsetdata$Sub_metering_2<-as.numeric(levels(subsetdata$Sub_metering_2)[subsetdata$Sub_metering_2])
subsetdata$Sub_metering_3<-as.numeric(levels(subsetdata$Sub_metering_3)[subsetdata$Sub_metering_3])
par(mar=c(5.1,5.1,4,1.5))
energy_sub_metering<-c(subsetdata$Sub_metering_1,subsetdata$Sub_metering_2,subsetdata$Sub_metering_3)
with(subsetdata,plot(subsetdata$Time, subsetdata$Sub_metering_1,xaxt="n",xlab="",ylab="Energy sub metering",type="l"))
points(subsetdata$Time,energy_sub_metering[1:2880],type="l")
points(subsetdata$Time,energy_sub_metering[2881:5760],type="l",col="Red")
points(subsetdata$Time,energy_sub_metering[5761:8640],type="l",col="Blue")
axis(1,at=c(4,5,6),labels=c("Thur","Fri","Sat"))
dev.copy(png,file="plot3.png")
dev.off()